name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pytest
    - name: Upload Coverage report
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: cov.html
        retention-days: 5
